C
C STABILITY CHECK OF D2 METHOD (SCOND ORDER DIFFERENCIG SCHEME)
C USE IMSL
C
C (C) TOSHIAKI IITAKA 1994
C REFERENCE: T.Iitaka, Phys. Rev. E49 (1994) 4684.
C
      PROGRAM ST2
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      PARAMETER(NDEG=2)
      COMPLEX*16  COEFF(NDEG+1),ROOT(NDEG),IU
      OPEN(20,FILE='st2.dat')
      DO 10 A=0.0, 1.0, 0.01
      IU=(0.0,1.0)
      COEFF(1)=-1
      COEFF(2)=2*IU*A
      COEFF(3)=1
      CALL DZPOCC(NDEG,COEFF,ROOT)
      DO 20 I=1,NDEG
      WRITE(*,100) A,REAL(ROOT(I)),IMAG(ROOT(I)),ABS(ROOT(I))-1
   20 CONTINUE
      WRITE(20,100) A,(REAL(ROOT(I)),IMAG(ROOT(I)),ABS(ROOT(I)),
     &I=1,NDEG)
  100 FORMAT(1H ,30E15.7)
   10 CONTINUE
      CLOSE(20)
      STOP
      END
